# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
warnings_are_errors: false
sudo: false

matrix:
  include:
  - r: release
    os: linux
    dist: bionic
  - r: release
    os: osx

r_check_args: --no-manual --no-examples