# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
add <- function(a, b) {
    .Call('_calcsoapR_add', PACKAGE = 'calcsoapR', a, b)
}

#' @export
sub <- function(a, b) {
    .Call('_calcsoapR_sub', PACKAGE = 'calcsoapR', a, b)
}

#' @export
mul <- function(a, b) {
    .Call('_calcsoapR_mul', PACKAGE = 'calcsoapR', a, b)
}

#' @export
div <- function(a, b) {
    .Call('_calcsoapR_div', PACKAGE = 'calcsoapR', a, b)
}

#' @export
pow <- function(a, b) {
    .Call('_calcsoapR_pow', PACKAGE = 'calcsoapR', a, b)
}

