# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Addition
#' @description Add two numbers
#' @param a numeric;
#' @param b numeric;
#' @return numeric; sum of a and b
#' @export
add <- function(a, b) {
    .Call(`_calcsoapR_add`, a, b)
}

#' Subtraction
#' @description Subtact two numbers
#' @param a numeric;
#' @param b numeric;
#' @return numeric; difference of a and b
#' @export
sub <- function(a, b) {
    .Call(`_calcsoapR_sub`, a, b)
}

#' Multiplication
#' @description Multiply two numbers
#' @param a numeric;
#' @param b numeric;
#' @return numeric; product of a and b
#' @export
mul <- function(a, b) {
    .Call(`_calcsoapR_mul`, a, b)
}

#' Division
#' @description Divide two numbers
#' @param a numeric;
#' @param b numeric;
#' @return numeric; division of a and b
#' @export
div <- function(a, b) {
    .Call(`_calcsoapR_div`, a, b)
}

#' Exponentiation
#' @description Exponentiate two numbers
#' @param a numeric;
#' @param b numeric;
#' @return numeric; a to the b power
#' @export
pow <- function(a, b) {
    .Call(`_calcsoapR_pow`, a, b)
}

