# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
add <- function(a, b) {
    .Call('_calcsoap_add', PACKAGE = 'calcsoap', a, b)
}

#' @export
sub <- function(a, b) {
    .Call('_calcsoap_sub', PACKAGE = 'calcsoap', a, b)
}

#' @export
mul <- function(a, b) {
    .Call('_calcsoap_mul', PACKAGE = 'calcsoap', a, b)
}

#' @export
div <- function(a, b) {
    .Call('_calcsoap_div', PACKAGE = 'calcsoap', a, b)
}

#' @export
pow <- function(a, b) {
    .Call('_calcsoap_pow', PACKAGE = 'calcsoap', a, b)
}

